[[redirects]]
  from = "/blogs/markoshust"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/comment/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "/newsletter/subscribe-marks-newsletter"
  to = "/newsletter/"
  status = 301
  force = true
[[redirects]]
  from = "/magento-extensions/*"
  to = "/"
  status = 301
  force = true
[[redirects]]
  from = "https://markshust-com.netlify.com/*"
  to = "https://markshust.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://markshust-com.netlify.com/"
  to = "https://markshust.com/"
  status = 301
  force = true
[[redirects]]
  from = "https://markshust.com/courses/*"
  to = "https://courses.markshust.com/"
  status = 301
  force = true
